# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              https://github.com/shaccou/penguin
paginate:         1
baseurl:          http://shaccou.github.io/penguin/
author:
  name:           Sophia Haccou
  url:            https://twitter.com/fluffenator
  email:          sophia.haccou@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/shaccou/penguin
